### ISSUE TITLE
Can't find folder/files inside directories on Windows

### ISSUE THREAD

**Issue by lMagickl** [quentinguidee/gitignore-ultimate#3] opened 2022-05-09 10:06 UTC
Hi,

![image](https://user-images.githubusercontent.com/33726502/167387837-0a682427-46c7-443c-8641-62cad52e5db3.png)

VSCode 1.66.2
OS: Win11
Extension: 0.1.7

maybe i dont use it the wright way

**Comment by quentinguidee** [comment] 2022-05-09 10:13
Hi,

This is strange, it should work as expected, and I just tested on my computer and it works well with this version.

* Is the file type correctly marked as `gitignore (ignore)` file ?
* Is the name of the file `.gitignore` ?
* Are you using workspace or not ?

**Comment by lMagickl** [comment] 2022-05-09 10:27
Is the file type correctly marked as gitignore (ignore) file ? =>how can I check this ?
Is the name of the file .gitignore ? => yes
Are you using workspace or not ? => yes

**Comment by lMagickl** [comment] 2022-05-09 11:03
it work if i use the version 0.1.4 and below and it crashes in the 0.1.5 only
with this log if it can help you to fix

`c:\Users\Magic\.vscode\extensions\quentinguidee.gitignore-ultimate-0.1.5\server\out\server.js:58
            files.forEach((file) => {
                  ^

TypeError: Cannot read properties of undefined (reading 'forEach')
    at getFilesAndFolders (c:\Users\Magic\.vscode\extensions\quentinguidee.gitignore-ultimate-0.1.5\server\out\server.js:58:19)
    at node:fs:188:23
    at FSReqCallback.req.oncomplete (node:fs:1364:9)
[Info  - 13:02:36] Connection to server got closed. Server will restart.
[Error - 13:02:36] Request textDocument/completion failed.
Error: Connection got disposed.
    at Object.dispose (c:\Users\Magic\.vscode\extensions\quentinguidee.gitignore-ultimate-0.1.5\client\node_modules\vscode-jsonrpc\lib\common\connection.js:1044:27)
    at Object.dispose (c:\Users\Magic\.vscode\extensions\quentinguidee.gitignore-ultimate-0.1.5\client\node_modules\vscode-languageclient\lib\common\client.js:73:35)
    at LanguageClient.handleConnectionClosed (c:\Users\Magic\.vscode\extensions\quentinguidee.gitignore-ultimate-0.1.5\client\node_modules\vscode-languageclient\lib\common\client.js:2424:42)
    at LanguageClient.handleConnectionClosed (c:\Users\Magic\.vscode\extensions\quentinguidee.gitignore-ultimate-0.1.5\client\node_modules\vscode-languageclient\lib\node\main.js:155:15)
    at closeHandler (c:\Users\Magic\.vscode\extensions\quentinguidee.gitignore-ultimate-0.1.5\client\node_modules\vscode-languageclient\lib\common\client.js:2411:18)
    at CallbackList.invoke (c:\Users\Magic\.vscode\extensions\quentinguidee.gitignore-ultimate-0.1.5\client\node_modules\vscode-jsonrpc\lib\common\events.js:55:39)
    at Emitter.fire (c:\Users\Magic\.vscode\extensions\quentinguidee.gitignore-ultimate-0.1.5\client\node_modules\vscode-jsonrpc\lib\common\events.js:117:36)
    at closeHandler (c:\Users\Magic\.vscode\extensions\quentinguidee.gitignore-ultimate-0.1.5\client\node_modules\vscode-jsonrpc\lib\common\connection.js:256:26)
    at CallbackList.invoke (c:\Users\Magic\.vscode\extensions\quentinguidee.gitignore-ultimate-0.1.5\client\node_modules\vscode-jsonrpc\lib\common\events.js:55:39)
    at Emitter.fire (c:\Users\Magic\.vscode\extensions\quentinguidee.gitignore-ultimate-0.1.5\client\node_modules\vscode-jsonrpc\lib\common\events.js:117:36)
    at IPCMessageReader.fireClose (c:\Users\Magic\.vscode\extensions\quentinguidee.gitignore-ultimate-0.1.5\client\node_modules\vscode-jsonrpc\lib\common\messageReader.js:40:27)
    at ChildProcess.<anonymous> (c:\Users\Magic\.vscode\extensions\quentinguidee.gitignore-ultimate-0.1.5\client\node_modules\vscode-jsonrpc\lib\node\main.js:33:45)
    at ChildProcess.emit (node:events:402:35)
    at ChildProcess.emit (node:domain:475:12)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)`

**Comment by quentinguidee** [comment] 2022-05-15 16:17
Hi!

It's really strange, I can't reproduce this bug.

![image](https://user-images.githubusercontent.com/12123721/168482700-c7be0a19-058c-4ba1-9bb9-45bae5117bd7.png)

My sample project is configured like this :

```
Workspace
  src/
    workers/
  .gitignore
```

> Is the file type correctly marked as gitignore (ignore) file ? =>how can I check this ?

You should see "gitignore" at the bottom :
![image](https://user-images.githubusercontent.com/12123721/168482788-fec3b974-dccb-4e99-8be2-c8b6b88819da.png)

**Comment by quentinguidee** [comment] 2022-05-15 16:18
Maybe… Are you on Windows ?

**Comment by lMagickl** [comment] 2022-05-15 17:28
yes i am on windows and i checked the gitignore and he well marked as gitignore

**Comment by quentinguidee** [comment] 2022-05-15 18:08
I think it should be fixed with #4 

Since I can't test on Windows, could you try this extension on your computer? [Google Drive link](https://drive.google.com/file/d/1BS-C6iaC50GHPaDf4TA6mSoRx99UZnQY/view?usp=sharing) (it's marked 0.1.7 but it isn't)

Thanks!

**Comment by lMagickl** [comment] 2022-05-15 18:15
its is working :)

**Comment by quentinguidee** [comment] 2022-05-15 18:19
Thanks! I publish that now

**Closed** 2022-05-15 18:18 UTC
Labels: bug

**Comment by quentinguidee** [comment] 2022-05-15 18:26
Thanks again! It should be published now (v0.1.8)
